#!/bin/bash

FILE="/var/tmp/checksum"
FILE_TO_WATCH="/etc/crontab"
MD5VALUE=$(md5sum $FILE_TO_WATCH)
if [ ! -f $FILE ]
then
	echo "$MD5VALUE" > $FILE
	exit 0;
fi;

if [ "$MD5VALUE" != "$(cat $FILE)" ];
	then
	echo "$MD5VALUE" > $FILE
	echo "$FILE_TO_WATCH has been modified ! '*_*" | mail -s "$FILE_TO_WATCH modified !" root
fi;
#Pour la planifiation il suffit de lancer la commande "crontab -e" puis d'éditer avec "0 0 * * * $PATH"
